repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Find the latest tag here: https://github.com/astral-sh/ruff-pre-commit/releases
    rev: v0.4.4
    hooks:
      # Run the linter and automatically fix issues.
      - id: ruff
        args: [--fix]
      # Run the formatter.
      - id: ruff-format