repos:
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: .venv/bin/mypy
        language: python
        types: [python]
      - id: ruff-check 
        name: ruff-check
        entry: .venv/bin/ruff check --force-exclude
        language: python
        types: [python]
      - id: ruff-format
        name: ruff-format
        entry: .venv/bin/ruff format --force-exclude
        language: python
        types: [python]